### ISSUE TITLE
Dynamic Responses

### ISSUE THREAD

**Issue by archetypalsxe** [archetypalsxe/api-simulator#12]
- [x] #13 - Pull data from requests
- [x] #15 - Add a Wildcard Field for APIs
- [ ] #16 - Ability to test settings
- [ ] Store or hold data from requests
- [ ] Use stored/held data in responses
